on: [push]

jobs:
 build:
  name: Build
  runs-on: ubuntu-20.04
  steps:   
    - uses: actions/checkout@v3   
    - run: |
        pwd
    - name: Google OSV scanner
      uses: google/osv-scanner@v1.0.1
      with: 
       args: --help       
    - run: |
        pwd
        ls
      if: always()
    - uses: actions/upload-artifact@v3
      if: always()
      with:
       name: my-artifact
       path: results.json
       
      
      
