on: [push]

jobs:
 build:
  name: Build
  runs-on: ubuntu-20.04
  steps:   
    - uses: actions/checkout@v3   
    - run: |
        pwd
    
    - name: Install a binary from GitHub releases
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with: # Grab the latest version
         repo: google/osv-scanner
         tag: v1.0.2
         extension-matching: disable
         rename-to: osv-scanner
         chmod: 0755
    
    - run: |
        pwd
        ls
        osv-scanner -r . --json
      if: always()
    - uses: actions/upload-artifact@v3
      if: always()
      with:
       name: my-artifact
       path: results.json
       
      
      
