on: [push]

jobs:
 build:
  name: Build
  runs-on: ubuntu-20.04
  steps:   
    - uses: actions/checkout@v3   
    - run: |
        pwd
    - name: Google OSV scanner
      uses: google/osv-scanner@main
      with: 
       to-scan: /home/runner/work/vulnerable-app/vulnerable-app
      
      
      
